version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:latest
        environment:
          - ENV: CI
    working_directory: /

    steps:
     - run: |
         nix-env -i git
         git clone https://github.com/NixOS/nixpkgs.git
         cd nixpkgs
         nix-build -A netboot nixos/release.nix
         cat result/netboot.ipxe
         sha256sum result/bzImage >> result/sha256.txt
         sha256sum result/initrd >> result/sha256.txt
         cat result/sha256.txt
