version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:latest
        environment:
          - ENV: CI
    working_directory: /

    steps:
     - run: |
         nix-build -A netboot nixos/release.nix
