version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:latest
        environment:
          - ENV: CI
    working_directory: /

    steps:
     - run: |
         nix-env -i git
         git clone https://github.com/NixOS/nixpkgs.git
         cd nixpkgs/nixos
         nix-build -A netboot nixos/release.nix

